# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/partone/Basys-3-Master.xdc

# Block Designs: bd/axi_system/axi_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system || ORIG_REF_NAME==axi_system} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_spi_axi_0_0/axi_system_spi_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_spi_axi_0_0 || ORIG_REF_NAME==axi_system_spi_axi_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_microblaze_0_0/axi_system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_microblaze_0_0 || ORIG_REF_NAME==axi_system_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_uart_two_0_0/axi_system_uart_two_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_uart_two_0_0 || ORIG_REF_NAME==axi_system_uart_two_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_timer_two_0_0/axi_system_timer_two_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_timer_two_0_0 || ORIG_REF_NAME==axi_system_timer_two_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_gpio_0_0/axi_system_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_gpio_0_0 || ORIG_REF_NAME==axi_system_gpio_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_gpio_1_0/axi_system_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_gpio_1_0 || ORIG_REF_NAME==axi_system_gpio_1_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_gpio_1_1/axi_system_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_gpio_1_1 || ORIG_REF_NAME==axi_system_gpio_1_1} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_gpio_1_2/axi_system_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_gpio_1_2 || ORIG_REF_NAME==axi_system_gpio_1_2} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_gpio_1_3/axi_system_gpio_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_gpio_1_3 || ORIG_REF_NAME==axi_system_gpio_1_3} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_axi_intc_0_0/axi_system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_axi_intc_0_0 || ORIG_REF_NAME==axi_system_axi_intc_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_xlconcat_0_0/axi_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_xlconcat_0_0 || ORIG_REF_NAME==axi_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_dlmb_v10_0/axi_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_dlmb_v10_0 || ORIG_REF_NAME==axi_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_ilmb_v10_0/axi_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_ilmb_v10_0 || ORIG_REF_NAME==axi_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_dlmb_bram_if_cntlr_0/axi_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_ilmb_bram_if_cntlr_0/axi_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_lmb_bram_0/axi_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_lmb_bram_0 || ORIG_REF_NAME==axi_system_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_mdm_1_0/axi_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_mdm_1_0 || ORIG_REF_NAME==axi_system_mdm_1_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_clk_wiz_1_0/axi_system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_clk_wiz_1_0 || ORIG_REF_NAME==axi_system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_rst_clk_wiz_1_100M_0/axi_system_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_xbar_0/axi_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_xbar_0 || ORIG_REF_NAME==axi_system_xbar_0} -quiet] -quiet

# IP: bd/axi_system/ip/axi_system_microblaze_0_axi_periph_0/axi_system_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==axi_system_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_microblaze_0_0/axi_system_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_microblaze_0_0 || ORIG_REF_NAME==axi_system_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_microblaze_0_0/axi_system_microblaze_0_0_ooc_debug.xdc

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_axi_intc_0_0/axi_system_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_intc_0_0 || ORIG_REF_NAME==axi_system_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_axi_intc_0_0/axi_system_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_axi_intc_0_0 || ORIG_REF_NAME==axi_system_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_axi_intc_0_0/axi_system_axi_intc_0_0_ooc.xdc

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_lmb_bram_0/axi_system_lmb_bram_0_ooc.xdc

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_mdm_1_0/axi_system_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_mdm_1_0 || ORIG_REF_NAME==axi_system_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_mdm_1_0/axi_system_mdm_1_0_ooc_trace.xdc

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_clk_wiz_1_0/axi_system_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_clk_wiz_1_0 || ORIG_REF_NAME==axi_system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_clk_wiz_1_0/axi_system_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_clk_wiz_1_0 || ORIG_REF_NAME==axi_system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_clk_wiz_1_0/axi_system_clk_wiz_1_0_ooc.xdc

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_rst_clk_wiz_1_100M_0/axi_system_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_system_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/ip/axi_system_rst_clk_wiz_1_100M_0/axi_system_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_system_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/jh_workspace/0629_axi_spi_uart_timer_gpio/0629_axi_spi_uart_timer_gpio.gen/sources_1/bd/axi_system/axi_system_ooc.xdc
