
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 7.3
 PARAMETER PROC_INSTANCE = microblaze_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.12
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = axi_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = gpio_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = gpio_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = gpio_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = gpio_lcd_bl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi_axi
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = spi_axi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = timer_two
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = timer_two_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uart_two
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = uart_two_0
END


